import { ICart } from "../pages/PlantProtection/PlantProtection";

export const catalogItems: ICart[] = [
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: false,
    quantity: 2,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 2,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: false,
    quantity: 3,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
  {
    imgUrl: "/images/skor.png",
    scaleIcon: "/icons/scaleCart.svg",
    cartIcon: "icons/cart.svg",
    price: "200",
    id: "1",
    name: "Скор 250 ЕС к.э.",
    inStock: true,
    quantity: 1,
  },
];
